<?php

// UI strings: Alignments (Index.jsx, Create.jsx, Show.jsx, components/*).
return [
    'alignments.title' => ['en' => 'Alignments', 'ru' => 'Выравнивания'],
    'alignments.aligned_entity_pairs' => ['en' => 'Aligned entity pairs', 'ru' => 'Сопоставленные пары сущностей'],
    'alignments.pair' => ['en' => 'pair', 'ru' => 'пара'],
    'alignments.pairs' => ['en' => 'pairs', 'ru' => 'пар'],
    'alignments.create_new' => ['en' => '+ Create new', 'ru' => '+ Создать'],
    'alignments.th_a_entity' => ['en' => 'A entity', 'ru' => 'Сущность A'],
    'alignments.th_b_entity' => ['en' => 'B entity', 'ru' => 'Сущность B'],
    'alignments.th_similarity' => ['en' => 'Similarity', 'ru' => 'Сходство'],
    'alignments.th_progress' => ['en' => 'Progress', 'ru' => 'Прогресс'],
    'alignments.th_a_sents' => ['en' => 'A sents', 'ru' => 'Фраз A'],
    'alignments.th_b_sents' => ['en' => 'B sents', 'ru' => 'Фраз B'],
    'alignments.th_status' => ['en' => 'Status', 'ru' => 'Статус'],
    'alignments.th_created' => ['en' => 'Created', 'ru' => 'Создано'],
    'alignments.th_open' => ['en' => 'Open', 'ru' => 'Открыть'],
    'alignments.no_alignments_yet' => ['en' => 'No alignments yet.', 'ru' => 'Выравниваний пока нет.'],
    'alignments.no_alignments_hint' => ['en' => 'Run the alignment pipeline to produce a pair.', 'ru' => 'Запустите конвейер выравнивания, чтобы получить пару.'],
    'alignments.pagination' => ['en' => 'Pagination', 'ru' => 'Постраничная навигация'],
    'alignments.previous_page' => ['en' => 'Previous page', 'ru' => 'Предыдущая страница'],
    'alignments.next_page' => ['en' => 'Next page', 'ru' => 'Следующая страница'],
    'alignments.prev' => ['en' => '← Prev', 'ru' => '← Назад'],
    'alignments.next' => ['en' => 'Next →', 'ru' => 'Далее →'],
    'alignments.back' => ['en' => '← Alignments', 'ru' => '← Выравнивания'],
    'alignments.new_entity_match' => ['en' => 'New entity match', 'ru' => 'Новое сопоставление сущностей'],
    'alignments.create_heading' => ['en' => 'Align two translations of a work', 'ru' => 'Выровнять два перевода произведения'],
    'alignments.entities' => ['en' => 'Entities', 'ru' => 'Сущности'],
    'alignments.work' => ['en' => 'Work', 'ru' => 'Произведение'],
    'alignments.no_works' => ['en' => 'No works with alignable entities yet', 'ru' => 'Произведений с сущностями для выравнивания пока нет'],
    'alignments.work_hint' => ['en' => 'Both entities must belong to the same work (same language is fine, e.g. exercises and answers).', 'ru' => 'Обе сущности должны принадлежать одному произведению (язык может совпадать, например упражнения и ответы).'],
    'alignments.first_entity' => ['en' => 'First entity', 'ru' => 'Первая сущность'],
    'alignments.select_entity' => ['en' => 'Select an entity…', 'ru' => 'Выберите сущность…'],
    'alignments.second_entity' => ['en' => 'Second entity', 'ru' => 'Вторая сущность'],
    'alignments.second_entity_suffix' => ['en' => ' — other than :lang «:entity»', 'ru' => ' — кроме :lang «:entity»'],
    'alignments.chunk_size' => ['en' => 'Chunk size', 'ru' => 'Размер фрагмента'],
    'alignments.chunk_size_hint' => ['en' => 'Sentences per chunk (25–100).', 'ru' => 'Фраз на фрагмент (25–100).'],
    'alignments.max_n' => ['en' => 'Max sentence span', 'ru' => 'Максимальный охват фраз'],
    'alignments.max_n_hint' => ['en' => 'Alignment window size (1–8).', 'ru' => 'Размер окна выравнивания (1–8).'],
    'alignments.duplicate_match' => ['en' => 'A match for this entity pair already exists.', 'ru' => 'Сопоставление для этой пары сущностей уже существует.'],
    'alignments.open_existing_match' => ['en' => 'Open existing match →', 'ru' => 'Открыть существующее сопоставление →'],
    'alignments.create_match' => ['en' => 'Create match', 'ru' => 'Создать сопоставление'],
    'alignments.cancel' => ['en' => 'Cancel', 'ru' => 'Отмена'],
    'alignments.save' => ['en' => 'Save', 'ru' => 'Сохранить'],
    'alignments.linked_confirmed' => ['en' => ':linked linked / :confirmed confirmed', 'ru' => 'связано: :linked / подтверждено: :confirmed'],
    'alignments.sim' => ['en' => 'sim', 'ru' => 'сходство'],
    'alignments.changes_reverted' => ['en' => '— changes reverted', 'ru' => '— изменения отменены'],
    'alignments.load_error' => ['en' => 'Could not load pairs.', 'ru' => 'Не удалось загрузить пары.'],
    'alignments.no_pairs_yet' => ['en' => 'No pairs yet.', 'ru' => 'Пар пока нет.'],
    'alignments.no_pairs_hint' => ['en' => 'Run the alignment pipeline or drag sentences from Unmatched into a new pair.', 'ru' => 'Запустите конвейер выравнивания или перетащите фразы из «Нераспределённые» в новую пару.'],
    'alignments.unmatched' => ['en' => 'Unmatched', 'ru' => 'Нераспределённые'],
    'alignments.needs_review' => ['en' => 'Needs review', 'ru' => 'Требуют проверки'],
    'alignments.add' => ['en' => '+ Add', 'ru' => '+ Добавить'],
    'alignments.new_sentence' => ['en' => 'New :side sentence…', 'ru' => 'Новая фраза (:side)…'],
    'alignments.save_hint' => ['en' => 'Save (⌘+Enter)', 'ru' => 'Сохранить (⌘+Enter)'],
    'alignments.cancel_hint' => ['en' => 'Cancel (Esc)', 'ru' => 'Отменить (Esc)'],
    'alignments.empty_column' => ['en' => 'empty — drop or add a sentence', 'ru' => 'пусто — перетащите или добавьте фразу'],
    'alignments.approve' => ['en' => 'Approve', 'ru' => 'Подтвердить'],
    'alignments.approve_pair' => ['en' => 'Approve pair', 'ru' => 'Подтвердить пару'],
    'alignments.create_below' => ['en' => 'Create below', 'ru' => 'Создать ниже'],
    'alignments.delete' => ['en' => 'Delete', 'ru' => 'Удалить'],
    'alignments.delete_pair' => ['en' => 'Delete pair', 'ru' => 'Удалить пару'],
    'alignments.delete_pair_hint' => ['en' => 'Delete pair — sentences move to unmatched', 'ru' => 'Удалить пару — фразы перейдут в нераспределённые'],
    'alignments.drop_here' => ['en' => 'drop here', 'ru' => 'перетащите сюда'],
    'alignments.drop' => ['en' => 'drop', 'ru' => 'перетащите'],
    'alignments.drag_to_move' => ['en' => 'Drag to move', 'ru' => 'Перетащите, чтобы переместить'],
    'alignments.sentence_placeholder' => ['en' => 'Sentence text…', 'ru' => 'Текст фразы…'],
    'alignments.edit' => ['en' => 'Edit', 'ru' => 'Изменить'],
    'alignments.edit_sentence' => ['en' => 'Edit sentence', 'ru' => 'Изменить фразу'],
    'alignments.unlink_sentence' => ['en' => 'Unlink sentence', 'ru' => 'Отвязать фразу'],
    'alignments.unlink_hint' => ['en' => 'Unlink — move to unmatched', 'ru' => 'Отвязать — переместить в нераспределённые'],
    'alignments.delete_sentence' => ['en' => 'Delete sentence', 'ru' => 'Удалить фразу'],
    'alignments.delete_permanently' => ['en' => 'Delete permanently', 'ru' => 'Удалить безвозвратно'],
    'alignments.none' => ['en' => 'none', 'ru' => 'нет'],
    'alignments.prev_unmatched_page' => ['en' => 'Previous unmatched page', 'ru' => 'Предыдущая страница нераспределённых'],
    'alignments.next_unmatched_page' => ['en' => 'Next unmatched page', 'ru' => 'Следующая страница нераспределённых'],
    'alignments.one_sided' => ['en' => '1-sided', 'ru' => 'односторонняя'],
    'alignments.page_short' => ['en' => '→ p. :page', 'ru' => '→ стр. :page'],
    'alignments.nothing_needs_review' => ['en' => 'Nothing needs review.', 'ru' => 'Проверять нечего.'],
    'alignments.go_to_page' => ['en' => 'Go to page :page', 'ru' => 'Перейти на страницу :page'],
    'alignments.rows_per_page' => ['en' => 'Rows per page', 'ru' => 'Строк на странице'],
    'alignments.per_page' => ['en' => 'Per page', 'ru' => 'На странице'],
    'alignments.row' => ['en' => 'row', 'ru' => 'строка'],
    'alignments.rows' => ['en' => 'rows', 'ru' => 'строк'],
];
