<?php

// UI strings: Bilinguals (Bilinguals.jsx, Components/*).
return [
    'bilinguals.title' => ['en' => 'Bilinguals', 'ru' => 'Билингвы'],
    'bilinguals.add_api_key' => ['en' => 'Add an API key in your Profile to use the AI assistant.', 'ru' => 'Добавьте API-ключ в профиле, чтобы пользоваться ИИ-помощником.'],
    'bilinguals.load' => ['en' => 'Load', 'ru' => 'Загрузить'],
    'bilinguals.increase_font_size' => ['en' => 'Increase font size', 'ru' => 'Увеличить размер шрифта'],
    'bilinguals.decrease_font_size' => ['en' => 'Decrease font size', 'ru' => 'Уменьшить размер шрифта'],
    'bilinguals.text' => ['en' => 'Text', 'ru' => 'Текст'],
    'bilinguals.workplace' => ['en' => 'Workplace', 'ru' => 'Рабочее поле'],
    'bilinguals.question' => ['en' => 'Question', 'ru' => 'Вопрос'],
    'bilinguals.ai' => ['en' => 'AI', 'ru' => 'ИИ'],
    'bilinguals.rows_count' => ['en' => '· :total rows', 'ru' => '· строк: :total'],
    'bilinguals.previous' => ['en' => 'Previous', 'ru' => 'Назад'],
    'bilinguals.next' => ['en' => 'Next', 'ru' => 'Далее'],
    'bilinguals.page_number' => ['en' => 'Page number', 'ru' => 'Номер страницы'],
    'bilinguals.request_failed' => ['en' => 'Request failed (:status)', 'ru' => 'Не удалось выполнить запрос (:status)'],
    'bilinguals.failed_to_load_text' => ['en' => 'Failed to load text', 'ru' => 'Не удалось загрузить текст'],
    'bilinguals.couldnt_reach_model' => ['en' => "Couldn't reach the model.", 'ru' => 'Не удалось связаться с моделью.'],
    'bilinguals.couldnt_reach_model_header' => ['en' => "Couldn't reach the model", 'ru' => 'Не удалось связаться с моделью'],
    'bilinguals.couldnt_load' => ['en' => "Couldn't load", 'ru' => 'Не удалось загрузить'],
    'bilinguals.load_error_hint' => ['en' => 'Pick another text and load it, or try again in a moment.', 'ru' => 'Выберите другой текст и загрузите его или повторите попытку чуть позже.'],
    'bilinguals.no_text_loaded' => ['en' => 'No text loaded', 'ru' => 'Текст не загружен'],
    'bilinguals.press' => ['en' => 'Press', 'ru' => 'Нажмите'],
    'bilinguals.load_hint_tail' => ['en' => 'to bring in the selected text.', 'ru' => ', чтобы загрузить выбранный текст.'],
    'bilinguals.no_text_selected' => ['en' => 'No text selected', 'ru' => 'Текст не выбран'],
    'bilinguals.pick_text_hint' => ['en' => 'Pick a text and load it to start.', 'ru' => 'Выберите текст и загрузите его, чтобы начать.'],
    'bilinguals.english' => ['en' => 'English', 'ru' => 'Английский'],
    'bilinguals.russian' => ['en' => 'Russian', 'ru' => 'Русский'],
    'bilinguals.open' => ['en' => 'Open', 'ru' => 'Открыть'],
    'bilinguals.ask' => ['en' => 'Ask', 'ru' => 'Спросить'],
    'bilinguals.translation' => ['en' => 'Translation', 'ru' => 'Перевод'],
    'bilinguals.translation_placeholder' => ['en' => 'Write your translation here, then ask the reader to grade it.', 'ru' => 'Напишите здесь свой перевод, затем попросите читателя его оценить.'],
    'bilinguals.question_placeholder' => ['en' => 'Question', 'ru' => 'Вопрос'],
    'bilinguals.readers_gloss' => ['en' => "Reader's gloss", 'ru' => 'Пояснение читателя'],
    'bilinguals.ai_response' => ['en' => 'AI Response', 'ru' => 'Ответ ИИ'],
    'bilinguals.ask_again' => ['en' => 'Ask again', 'ru' => 'Спросить снова'],
    'bilinguals.working' => ['en' => 'Working', 'ru' => 'Работаем'],
    'bilinguals.retry' => ['en' => 'Retry', 'ru' => 'Повторить'],
    'bilinguals.ai_empty_hint' => ['en' => 'Open a row, write your translation to the left, then send. The reader will answer here.', 'ru' => 'Откройте строку, напишите свой перевод слева и отправьте. Читатель ответит здесь.'],
];
