<?php

// UI strings: crossword page.
return [
    'crossword.title' => ['en' => 'Crossword', 'ru' => 'Кроссворд'],
    'crossword.entity' => ['en' => 'Text', 'ru' => 'Текст'],
    'crossword.level' => ['en' => 'Word level', 'ru' => 'Уровень слов'],
    'crossword.build' => ['en' => 'Build', 'ru' => 'Собрать'],
    'crossword.level_0' => ['en' => 'A0', 'ru' => 'A0'],
    'crossword.level_1' => ['en' => 'A1', 'ru' => 'A1'],
    'crossword.level_2' => ['en' => 'A2', 'ru' => 'A2'],
    'crossword.level_3' => ['en' => 'B1', 'ru' => 'B1'],
    'crossword.level_4' => ['en' => 'B2', 'ru' => 'B2'],
    'crossword.level_5' => ['en' => 'C1', 'ru' => 'C1'],
    'crossword.level_6' => ['en' => 'C2', 'ru' => 'C2'],
    'crossword.level_7' => ['en' => 'Native', 'ru' => 'Носитель'],
    'crossword.tab_definitions' => ['en' => 'Definitions', 'ru' => 'Определения'],
    'crossword.tab_obsolete' => ['en' => 'Obsolete', 'ru' => 'Устаревшие'],
    'crossword.tab_translations' => ['en' => 'Translations', 'ru' => 'Переводы'],
    'crossword.tab_forms' => ['en' => 'Forms', 'ru' => 'Формы'],
    'crossword.image' => ['en' => 'Image', 'ru' => 'Картинка'],
    'crossword.know' => ['en' => 'I know this word', 'ru' => 'Я знаю это слово'],
    'crossword.show_unsolved' => ['en' => 'Show unsolved words', 'ru' => 'Показать нерешённые слова'],
    'crossword.unsolved' => ['en' => 'Unsolved words', 'ru' => 'Нерешённые слова'],
    'crossword.error' => ['en' => "Couldn't build", 'ru' => 'Не удалось собрать'],
    'crossword.error_hint' => ['en' => 'Something went wrong while generating the crossword.', 'ru' => 'Что-то пошло не так при генерации кроссворда.'],
    'crossword.retry' => ['en' => 'Retry', 'ru' => 'Повторить'],
    'crossword.no_crossword_loaded' => ['en' => 'No crossword loaded', 'ru' => 'Кроссворд не загружен'],
    'crossword.pick_and_build' => [
        'en' => 'Pick a text and a level, then press Build to generate a crossword.',
        'ru' => 'Выберите текст и уровень, затем нажмите «Собрать», чтобы сгенерировать кроссворд.',
    ],
    'crossword.no_crossword' => ['en' => 'No crossword loaded.', 'ru' => 'Кроссворд не загружен.'],
    'crossword.all_solved' => ['en' => 'All solved.', 'ru' => 'Всё решено.'],
    'crossword.nothing_here' => ['en' => 'Nothing here yet', 'ru' => 'Пока ничего нет'],
    'crossword.click_word' => ['en' => 'Click a word on the grid to see its entries.', 'ru' => 'Нажмите слово на сетке, чтобы увидеть его записи.'],
    'crossword.not_enough_words' => [
        'en' => 'Not enough dictionary words in this level band for this text. Link more dictionary words or pick another text or level.',
        'ru' => 'В этом уровне для текста недостаточно слов из словаря. Свяжите больше слов или выберите другой текст или уровень.',
    ],
];
