<?php

// UI strings: Entities pages (create, edit, details).
return [
    'entities.entities' => ['en' => 'entities', 'ru' => 'тексты'],
    'entities.new_entity' => ['en' => 'New entity', 'ru' => 'Новый текст'],
    'entities.create_a_entity' => ['en' => 'Create a :code entity', 'ru' => 'Создать текст (:code)'],
    'entities.work' => ['en' => 'Work', 'ru' => 'Произведение'],
    'entities.existing_work' => ['en' => 'Existing work', 'ru' => 'Существующее произведение'],
    'entities.new_work' => ['en' => 'New work', 'ru' => 'Новое произведение'],
    'entities.work_title_placeholder' => ['en' => 'Work title (e.g. War and Peace)', 'ru' => 'Название произведения (например, «Война и мир»)'],
    'entities.author_optional' => ['en' => 'Author (optional)', 'ru' => 'Автор (необязательно)'],
    'entities.original_language_defaults' => ['en' => 'Original language — defaults to :name', 'ru' => 'Язык оригинала — по умолчанию :name'],
    'entities.this_text' => ['en' => ' (this text)', 'ru' => ' (этот текст)'],
    'entities.name' => ['en' => 'Name', 'ru' => 'Название'],
    'entities.translator_edition_note' => ['en' => 'Translator / edition note', 'ru' => 'Примечание о переводе / издании'],
    'entities.label_placeholder' => ['en' => 'Optional — tells same-language entities of one work apart', 'ru' => 'Необязательно — различает тексты одного произведения на одном языке'],
    'entities.description' => ['en' => 'Description', 'ru' => 'Описание'],
    'entities.text_file' => ['en' => 'Text file', 'ru' => 'Текстовый файл'],
    'entities.text_file_hint' => ['en' => 'Optional. A plain text (.txt) file. If provided, it is split into sentences and a signature is generated.', 'ru' => 'Необязательно. Обычный текстовый файл (.txt). Если загружен, он разбивается на предложения и для него генерируется сигнатура.'],
    'entities.create_entity' => ['en' => 'Create entity', 'ru' => 'Создать текст'],
    'entities.cancel' => ['en' => 'Cancel', 'ru' => 'Отмена'],
    'entities.back_to' => ['en' => '← Back to :name', 'ru' => '← Вернуться к «:name»'],
    'entities.edit_entity' => ['en' => 'Edit entity', 'ru' => 'Редактирование текста'],
    'entities.save_metadata' => ['en' => 'Save metadata', 'ru' => 'Сохранить метаданные'],
    'entities.sentences' => ['en' => 'Sentences', 'ru' => 'Предложения'],
    'entities.part_of' => ['en' => 'Part of', 'ru' => 'Часть из'],
    'entities.alignment' => ['en' => 'alignment', 'ru' => 'выравнивания'],
    'entities.alignments' => ['en' => 'alignments', 'ru' => 'выравниваний'],
    'entities.loading_sentences' => ['en' => 'Loading sentences…', 'ru' => 'Загрузка предложений…'],
    'entities.no_sentences_yet' => ['en' => 'No sentences yet.', 'ru' => 'Предложений пока нет.'],
    'entities.add_first_sentence' => ['en' => 'Add the first sentence', 'ru' => 'Добавить первое предложение'],
    'entities.insert_below' => ['en' => 'Insert below', 'ru' => 'Вставить ниже'],
    'entities.add_sentence' => ['en' => 'Add sentence', 'ru' => 'Добавить предложение'],
    'entities.sentence_text_placeholder' => ['en' => 'Sentence text…', 'ru' => 'Текст предложения…'],
    'entities.type' => ['en' => 'Type', 'ru' => 'Тип'],
    'entities.select' => ['en' => 'Select…', 'ru' => 'Выберите…'],
    'entities.drag_to_move' => ['en' => 'Drag to move', 'ru' => 'Перетащите, чтобы переместить'],
    'entities.save' => ['en' => 'Save', 'ru' => 'Сохранить'],
    'entities.save_cmd_enter' => ['en' => 'Save (⌘+Enter)', 'ru' => 'Сохранить (⌘+Enter)'],
    'entities.cancel_esc' => ['en' => 'Cancel (Esc)', 'ru' => 'Отмена (Esc)'],
    'entities.edit_sentence' => ['en' => 'Edit sentence', 'ru' => 'Редактировать предложение'],
    'entities.edit' => ['en' => 'Edit', 'ru' => 'Редактировать'],
    'entities.add_sentence_below' => ['en' => 'Add sentence below', 'ru' => 'Добавить предложение ниже'],
    'entities.delete_sentence' => ['en' => 'Delete sentence', 'ru' => 'Удалить предложение'],
    'entities.delete_permanently' => ['en' => 'Delete permanently', 'ru' => 'Удалить навсегда'],
    'entities.delete_sentence_confirm' => ['en' => 'Delete this sentence? This cascades into any alignment it belongs to.', 'ru' => 'Удалить это предложение? Оно будет также удалено из всех выравниваний, в которые входит.'],
    'entities.validation_error' => ['en' => 'Validation error.', 'ru' => 'Ошибка проверки данных.'],
    'entities.signature_generated' => ['en' => 'Signature generated', 'ru' => 'Сигнатура сгенерирована'],
    'entities.signature_pending' => ['en' => 'Signature pending', 'ru' => 'Сигнатура формируется'],
    'entities.no_file' => ['en' => 'No file', 'ru' => 'Нет файла'],
    'entities.read' => ['en' => 'Read', 'ru' => 'Читать'],
    'entities.open_alignment' => ['en' => 'Open alignment', 'ru' => 'Открыть выравнивание'],
    'entities.source_file' => ['en' => 'Source file', 'ru' => 'Исходный файл'],
    'entities.signature' => ['en' => 'Signature', 'ru' => 'Сигнатура'],
    'entities.total' => ['en' => 'total', 'ru' => 'всего'],
    'entities.no_sentences_hint' => ['en' => 'No sentences yet. Upload a text file to generate them.', 'ru' => 'Предложений пока нет. Загрузите текстовый файл, чтобы их сгенерировать.'],
    'entities.pagination' => ['en' => 'Pagination', 'ru' => 'Разбивка на страницы'],
    'entities.prev' => ['en' => '← Prev', 'ru' => '← Назад'],
    'entities.next' => ['en' => 'Next →', 'ru' => 'Далее →'],
];
