<?php

// UI strings: Entities pages (edit, details).
return [
    'entities.entities' => ['en' => 'entities', 'ru' => 'тексты'],
    'entities.name' => ['en' => 'Name', 'ru' => 'Название'],
    'entities.description' => ['en' => 'Description', 'ru' => 'Описание'],
    'entities.cancel' => ['en' => 'Cancel', 'ru' => 'Отмена'],
    'entities.back_to' => ['en' => '← Back to :name', 'ru' => '← Вернуться к «:name»'],
    'entities.edit_entity' => ['en' => 'Edit entity', 'ru' => 'Редактирование текста'],
    'entities.save_metadata' => ['en' => 'Save metadata', 'ru' => 'Сохранить метаданные'],
    'entities.sentences' => ['en' => 'Sentences', 'ru' => 'Предложения'],
    'entities.part_of' => ['en' => 'Part of', 'ru' => 'Часть из'],
    'entities.alignment' => ['en' => 'alignment', 'ru' => 'выравнивания'],
    'entities.alignments' => ['en' => 'alignments', 'ru' => 'выравниваний'],
    'entities.loading_sentences' => ['en' => 'Loading sentences…', 'ru' => 'Загрузка предложений…'],
    'entities.no_sentences_yet' => ['en' => 'No sentences yet.', 'ru' => 'Предложений пока нет.'],
    'entities.add_first_sentence' => ['en' => 'Add the first sentence', 'ru' => 'Добавить первое предложение'],
    'entities.insert_below' => ['en' => 'Insert below', 'ru' => 'Вставить ниже'],
    'entities.add_sentence' => ['en' => 'Add sentence', 'ru' => 'Добавить предложение'],
    'entities.sentence_text_placeholder' => ['en' => 'Sentence text…', 'ru' => 'Текст предложения…'],
    'entities.type' => ['en' => 'Type', 'ru' => 'Тип'],
    'entities.select' => ['en' => 'Select…', 'ru' => 'Выберите…'],
    'entities.drag_to_move' => ['en' => 'Drag to move', 'ru' => 'Перетащите, чтобы переместить'],
    'entities.save' => ['en' => 'Save', 'ru' => 'Сохранить'],
    'entities.save_cmd_enter' => ['en' => 'Save (⌘+Enter)', 'ru' => 'Сохранить (⌘+Enter)'],
    'entities.cancel_esc' => ['en' => 'Cancel (Esc)', 'ru' => 'Отмена (Esc)'],
    'entities.edit_sentence' => ['en' => 'Edit sentence', 'ru' => 'Редактировать предложение'],
    'entities.edit' => ['en' => 'Edit', 'ru' => 'Редактировать'],
    'entities.add_sentence_below' => ['en' => 'Add sentence below', 'ru' => 'Добавить предложение ниже'],
    'entities.delete_sentence' => ['en' => 'Delete sentence', 'ru' => 'Удалить предложение'],
    'entities.delete_permanently' => ['en' => 'Delete permanently', 'ru' => 'Удалить навсегда'],
    'entities.delete_sentence_confirm' => ['en' => 'Delete this sentence? This cascades into any alignment it belongs to.', 'ru' => 'Удалить это предложение? Оно будет также удалено из всех выравниваний, в которые входит.'],
    'entities.validation_error' => ['en' => 'Validation error.', 'ru' => 'Ошибка проверки данных.'],
    'entities.signature_generated' => ['en' => 'Signature generated', 'ru' => 'Сигнатура сгенерирована'],
    'entities.signature_pending' => ['en' => 'Signature pending', 'ru' => 'Сигнатура формируется'],
    'entities.no_file' => ['en' => 'No file', 'ru' => 'Нет файла'],
    'entities.limit_reached' => ['en' => 'You already have the maximum number of entities being processed. Wait for one to finish before uploading another.', 'ru' => 'У вас уже обрабатывается максимальное количество текстов. Дождитесь завершения одного из них, прежде чем загружать новый.'],
    'entities.read' => ['en' => 'Read', 'ru' => 'Читать'],
    'entities.open_alignment' => ['en' => 'Open alignment', 'ru' => 'Открыть выравнивание'],
    'entities.source_file' => ['en' => 'Source file', 'ru' => 'Исходный файл'],
    'entities.signature' => ['en' => 'Signature', 'ru' => 'Сигнатура'],
    'entities.total' => ['en' => 'total', 'ru' => 'всего'],
    'entities.no_sentences_hint' => ['en' => 'No sentences yet. Upload a text file to generate them.', 'ru' => 'Предложений пока нет. Загрузите текстовый файл, чтобы их сгенерировать.'],
    'entities.pagination' => ['en' => 'Pagination', 'ru' => 'Разбивка на страницы'],
    'entities.prev' => ['en' => '← Prev', 'ru' => '← Назад'],
    'entities.next' => ['en' => 'Next →', 'ru' => 'Далее →'],
    'entities.approved' => ['en' => 'Approved', 'ru' => 'Утверждено'],
    'entities.approved_hint' => ['en' => 'Approved — the text and its alignments are locked for editing.', 'ru' => 'Утверждено — текст и его выравнивания защищены от редактирования.'],
    'entities.approve' => ['en' => 'Approve', 'ru' => 'Утвердить'],
    'entities.unapprove' => ['en' => 'Remove approval', 'ru' => 'Снять утверждение'],
    'entities.caption_placeholder' => ['en' => 'Caption (optional)…', 'ru' => 'Подпись (необязательно)…'],
    'entities.image_file' => ['en' => 'Image — jpg, png, webp or gif, up to 10 MB', 'ru' => 'Изображение — jpg, png, webp или gif, до 10 МБ'],
    'entities.replace_image' => ['en' => 'Replace image', 'ru' => 'Заменить изображение'],
    'entities.illustration_type_locked' => ['en' => 'An illustration keeps its type', 'ru' => 'Тип иллюстрации не меняется'],
    'entities.illustration' => ['en' => 'Illustration', 'ru' => 'Иллюстрация'],
];
