<?php

// UI strings: Library pages (works index, work creation, entity creation within library, work details).
return [
    'library.library' => ['en' => 'Library', 'ru' => 'Библиотека'],
    'library.works' => ['en' => 'Works', 'ru' => 'Произведения'],
    'library.search_works' => ['en' => 'Search works', 'ru' => 'Поиск произведений'],
    'library.search' => ['en' => 'Search', 'ru' => 'Найти'],
    'library.search_placeholder' => ['en' => 'Search by title or author…', 'ru' => 'Поиск по названию или автору…'],
    'library.add_work' => ['en' => 'Add work', 'ru' => 'Добавить произведение'],
    'library.add_a_work' => ['en' => 'Add a work', 'ru' => 'Добавить произведение'],
    'library.no_works_match' => ['en' => 'No works match “:q”.', 'ru' => 'По запросу «:q» ничего не найдено.'],
    'library.no_works_match_hint' => ['en' => 'Try another title or author, or add the work yourself.', 'ru' => 'Попробуйте другое название или автора либо добавьте произведение сами.'],
    'library.entity' => ['en' => 'entity', 'ru' => 'текст'],
    'library.entities' => ['en' => 'entities', 'ru' => 'текстов'],
    'library.original' => ['en' => 'original', 'ru' => 'оригинал'],
    'library.search_entities' => ['en' => 'Search entities', 'ru' => 'Поиск текстов'],
    'library.entities_search_placeholder' => ['en' => 'Search by name or label…', 'ru' => 'Поиск по названию или подписи…'],
    'library.add_entity' => ['en' => 'Add entity', 'ru' => 'Добавить текст'],
    'library.add_an_entity' => ['en' => 'Add an entity', 'ru' => 'Добавить текст'],
    'library.no_entities_match' => ['en' => 'No entities match “:q”.', 'ru' => 'По запросу «:q» ничего не найдено.'],
    'library.no_entities_match_hint' => ['en' => 'Entities you do not have access to are never listed.', 'ru' => 'Тексты, к которым у вас нет доступа, никогда не отображаются.'],
    'library.no_entities_yet' => ['en' => 'No entities yet.', 'ru' => 'Текстов пока нет.'],
    'library.no_entities_yet_hint' => ['en' => 'Add the first text of this work, or come back once one is shared with you.', 'ru' => 'Добавьте первый текст этого произведения или вернитесь, когда он появится в общем доступе.'],
    'library.sentence' => ['en' => 'sentence', 'ru' => 'предложение'],
    'library.sentences' => ['en' => 'sentences', 'ru' => 'предложений'],
    'library.title' => ['en' => 'Title', 'ru' => 'Название'],
    'library.work_title_placeholder' => ['en' => 'Work title (e.g. War and Peace)', 'ru' => 'Название произведения (например, «Война и мир»)'],
    'library.author' => ['en' => 'Author', 'ru' => 'Автор'],
    'library.optional' => ['en' => 'Optional', 'ru' => 'Необязательно'],
    'library.original_language' => ['en' => 'Original language', 'ru' => 'Язык оригинала'],
    'library.pick_a_language' => ['en' => 'Pick a language…', 'ru' => 'Выберите язык…'],
    'library.original_language_hint' => ['en' => 'The language the work was written in.', 'ru' => 'Язык, на котором написано произведение.'],
    'library.description' => ['en' => 'Description', 'ru' => 'Описание'],
    'library.create_work' => ['en' => 'Create work', 'ru' => 'Создать произведение'],
    'library.cancel' => ['en' => 'Cancel', 'ru' => 'Отмена'],
    'library.work' => ['en' => 'Work', 'ru' => 'Произведение'],
    'library.language' => ['en' => 'Language', 'ru' => 'Язык'],
    'library.pick_language_of_text' => ['en' => 'Pick the language of this text…', 'ru' => 'Выберите язык этого текста…'],
    'library.name' => ['en' => 'Name', 'ru' => 'Название'],
    'library.translator_edition_note' => ['en' => 'Translator / edition note', 'ru' => 'Примечание о переводе / издании'],
    'library.label_placeholder' => ['en' => 'Optional — tells same-language entities of one work apart', 'ru' => 'Необязательно — различает тексты одного произведения на одном языке'],
    'library.text_file' => ['en' => 'Text file', 'ru' => 'Текстовый файл'],
    'library.text_file_hint' => ['en' => 'Optional. A plain text (.txt) file. If provided, it is split into sentences and a signature is generated.', 'ru' => 'Необязательно. Обычный текстовый файл (.txt). Если загружен, он разбивается на предложения и для него генерируется сигнатура.'],
    'library.create_entity' => ['en' => 'Create entity', 'ru' => 'Создать текст'],
];
