<?php

// UI strings: profile (Profile/Edit page).
return [
    'profile.account_eyebrow' => ['en' => 'Account', 'ru' => 'Аккаунт'],
    'profile.profile_title' => ['en' => 'Profile', 'ru' => 'Профиль'],
    'profile.section_eyebrow' => ['en' => 'Section', 'ru' => 'Раздел'],
    'profile.profile_information_title' => ['en' => 'Profile Information', 'ru' => 'Информация профиля'],
    'profile.profile_information_description' => ['en' => "Update your account's profile information and email address.", 'ru' => 'Обновите информацию профиля и адрес электронной почты вашей учётной записи.'],
    'profile.name' => ['en' => 'Name', 'ru' => 'Имя'],
    'profile.email' => ['en' => 'Email', 'ru' => 'Email'],
    'profile.save_changes' => ['en' => 'Save changes', 'ru' => 'Сохранить изменения'],
    'profile.saved' => ['en' => 'Saved.', 'ru' => 'Сохранено.'],
    'profile.settings_title' => ['en' => 'Settings', 'ru' => 'Настройки'],
    'profile.settings_description' => ['en' => 'Choose your native language. It is used to tailor your learning experience.', 'ru' => 'Выберите родной язык. Он используется для персонализации вашего обучения.'],
    'profile.native_language' => ['en' => 'Native Language', 'ru' => 'Родной язык'],
    'profile.interface_language' => ['en' => 'Interface Language', 'ru' => 'Язык интерфейса'],
    'profile.follows_native_language' => ['en' => '— Follows native language —', 'ru' => '— Как родной язык —'],
    'profile.password_title' => ['en' => 'Password', 'ru' => 'Пароль'],
    'profile.password_description' => ['en' => 'Ensure your account is using a long, random password to stay secure.', 'ru' => 'Убедитесь, что ваша учётная запись использует длинный случайный пароль для большей безопасности.'],
    'profile.current_password' => ['en' => 'Current Password', 'ru' => 'Текущий пароль'],
    'profile.new_password' => ['en' => 'New Password', 'ru' => 'Новый пароль'],
    'profile.confirm_password' => ['en' => 'Confirm Password', 'ru' => 'Подтверждение пароля'],
    'profile.danger_eyebrow' => ['en' => 'Danger zone', 'ru' => 'Опасная зона'],
    'profile.delete_account_title' => ['en' => 'Delete Account', 'ru' => 'Удаление аккаунта'],
    'profile.delete_account' => ['en' => 'Delete Account', 'ru' => 'Удалить аккаунт'],
    'profile.delete_account_description' => ['en' => 'Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.', 'ru' => 'После удаления аккаунта все его ресурсы и данные будут удалены безвозвратно. Перед удалением аккаунта сохраните все данные или информацию, которые вы хотите оставить.'],
    'profile.delete_account_confirm_title' => ['en' => 'Are you sure you want to delete your account?', 'ru' => 'Вы уверены, что хотите удалить свой аккаунт?'],
    'profile.delete_account_confirm_description' => ['en' => 'Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.', 'ru' => 'После удаления аккаунта все его ресурсы и данные будут удалены безвозвратно. Введите пароль, чтобы подтвердить безвозвратное удаление аккаунта.'],
    'profile.password' => ['en' => 'Password', 'ru' => 'Пароль'],
    'profile.cancel' => ['en' => 'Cancel', 'ru' => 'Отмена'],
    'profile.remove_key' => ['en' => 'Remove key', 'ru' => 'Удалить ключ'],
    'profile.current_key' => ['en' => 'Current key:', 'ru' => 'Текущий ключ:'],
    'profile.paste_api_key' => ['en' => 'Paste your API key', 'ru' => 'Вставьте свой API-ключ'],
    'profile.save' => ['en' => 'Save', 'ru' => 'Сохранить'],
    'profile.api_keys_title' => ['en' => 'AI Provider API Keys', 'ru' => 'API-ключи ИИ-провайдеров'],
    'profile.api_keys_description' => ['en' => 'Add your own API keys to use AI providers in the simulator. Keys are encrypted; only the first and last four characters are shown back to you for identification. Requests are billed to your own provider account.', 'ru' => 'Добавьте свои API-ключи, чтобы использовать ИИ-провайдеров в симуляторе. Ключи шифруются; для идентификации вам показываются только первые и последние четыре символа. Запросы тарифицируются на ваш собственный аккаунт провайдера.'],
    'profile.tab_account' => ['en' => 'Account', 'ru' => 'Аккаунт'],
    'profile.tab_preferences' => ['en' => 'Preferences', 'ru' => 'Настройки'],
    'profile.tab_ai' => ['en' => 'AI Models', 'ru' => 'ИИ-модели'],
    'profile.tab_danger' => ['en' => 'Danger zone', 'ru' => 'Опасная зона'],
    'profile.ai_models_title' => ['en' => 'AI Models', 'ru' => 'ИИ-модели'],
    'profile.ai_models_description' => ['en' => 'The answer model powers AI answers in the simulator; the explanation model powers word explanations in the word popup. If no explanation model is chosen, the answer model is used. Requests are billed to your own provider account.', 'ru' => 'Модель ответов используется для ответов ИИ в симуляторе; модель объяснений — для объяснения слов во всплывающем окне. Если модель объяснений не выбрана, используется модель ответов. Запросы тарифицируются на ваш собственный аккаунт провайдера.'],
    'profile.answer_model' => ['en' => 'Answer model', 'ru' => 'Модель ответов'],
    'profile.explanation_model' => ['en' => 'Explanation model', 'ru' => 'Модель объяснений'],
    'profile.choose_answer_model' => ['en' => '— Choose a model —', 'ru' => '— Выберите модель —'],
    'profile.follows_answer_model' => ['en' => '— Follows answer model —', 'ru' => '— Как модель ответов —'],
    'profile.ai_no_key_hint' => ['en' => 'Add at least one provider API key below to choose models.', 'ru' => 'Добавьте хотя бы один API-ключ провайдера ниже, чтобы выбрать модели.'],
];
