<?php

// UI strings: Reader (ReaderApp.jsx).
return [
    'reader.back_to_library' => ['en' => '← Library', 'ru' => '← Библиотека'],
    'reader.untitled' => ['en' => 'Untitled', 'ru' => 'Без названия'],
    'reader.decrease_text_size' => ['en' => 'Decrease text size', 'ru' => 'Уменьшить размер текста'],
    'reader.increase_text_size' => ['en' => 'Increase text size', 'ru' => 'Увеличить размер текста'],
    'reader.show_all' => ['en' => 'Show all', 'ru' => 'Показать все'],
    'reader.stacked' => ['en' => 'Stacked', 'ru' => 'Друг под другом'],
    'reader.side_by_side' => ['en' => 'Side by side', 'ru' => 'Рядами'],
    'reader.normal_width' => ['en' => 'Normal width', 'ru' => 'Обычная ширина'],
    'reader.wide' => ['en' => 'Wide', 'ru' => 'Широкая'],
    'reader.pick_audio' => ['en' => 'Pick audio', 'ru' => 'Выбрать аудио'],
    'reader.play' => ['en' => 'Play', 'ru' => 'Воспроизвести'],
    'reader.pause' => ['en' => 'Pause', 'ru' => 'Пауза'],
    'reader.stop' => ['en' => 'Stop', 'ru' => 'Остановить'],
    'reader.audio_loaded' => ['en' => 'Loaded · :name', 'ru' => 'Загружено · :name'],
    'reader.playing' => ['en' => 'Playing', 'ru' => 'Воспроизведение'],
    'reader.paused' => ['en' => 'Paused', 'ru' => 'Пауза'],
    'reader.stopped' => ['en' => 'Stopped', 'ru' => 'Остановлено'],
    'reader.ended' => ['en' => 'Ended', 'ru' => 'Завершено'],
    'reader.cannot_play' => ['en' => 'Cannot play: :reason', 'ru' => 'Не удалось воспроизвести: :reason'],
    'reader.unknown_error' => ['en' => 'unknown error', 'ru' => 'неизвестная ошибка'],
    'reader.folio' => ['en' => 'Folio', 'ru' => 'Разворот'],
    'reader.line' => ['en' => 'line', 'ru' => 'строка'],
    'reader.lines' => ['en' => 'lines', 'ru' => 'строк'],
    'reader.pages' => ['en' => 'Pages', 'ru' => 'Страницы'],
    'reader.previous_page' => ['en' => 'Previous page', 'ru' => 'Предыдущая страница'],
    'reader.next_page' => ['en' => 'Next page', 'ru' => 'Следующая страница'],
    'reader.go_to_page' => ['en' => 'Go to page', 'ru' => 'Перейти к странице'],
    'reader.page_of' => ['en' => 'of :last', 'ru' => 'из :last'],
    'reader.hint' => ['en' => 'Tap a line to reveal its translation · Spacebar toggles audio playback', 'ru' => 'Нажмите на строку, чтобы увидеть перевод · Пробел включает и выключает аудио'],
    'reader.highlights' => ['en' => 'Highlights', 'ru' => 'Подсветка слов'],
];
