<?php

// UI strings: Reader (ReaderApp.jsx, ReaderIndexApp.jsx).
return [
    'reader.back_to_library' => ['en' => '← Library', 'ru' => '← Библиотека'],
    'reader.untitled' => ['en' => 'Untitled', 'ru' => 'Без названия'],
    'reader.decrease_text_size' => ['en' => 'Decrease text size', 'ru' => 'Уменьшить размер текста'],
    'reader.increase_text_size' => ['en' => 'Increase text size', 'ru' => 'Увеличить размер текста'],
    'reader.show_all' => ['en' => 'Show all', 'ru' => 'Показать все'],
    'reader.stacked' => ['en' => 'Stacked', 'ru' => 'Друг под другом'],
    'reader.side_by_side' => ['en' => 'Side by side', 'ru' => 'Рядами'],
    'reader.normal_width' => ['en' => 'Normal width', 'ru' => 'Обычная ширина'],
    'reader.wide' => ['en' => 'Wide', 'ru' => 'Широкая'],
    'reader.pick_audio' => ['en' => 'Pick audio', 'ru' => 'Выбрать аудио'],
    'reader.play' => ['en' => 'Play', 'ru' => 'Воспроизвести'],
    'reader.pause' => ['en' => 'Pause', 'ru' => 'Пауза'],
    'reader.stop' => ['en' => 'Stop', 'ru' => 'Остановить'],
    'reader.audio_loaded' => ['en' => 'Loaded · :name', 'ru' => 'Загружено · :name'],
    'reader.playing' => ['en' => 'Playing', 'ru' => 'Воспроизведение'],
    'reader.paused' => ['en' => 'Paused', 'ru' => 'Пауза'],
    'reader.stopped' => ['en' => 'Stopped', 'ru' => 'Остановлено'],
    'reader.ended' => ['en' => 'Ended', 'ru' => 'Завершено'],
    'reader.cannot_play' => ['en' => 'Cannot play: :reason', 'ru' => 'Не удалось воспроизвести: :reason'],
    'reader.unknown_error' => ['en' => 'unknown error', 'ru' => 'неизвестная ошибка'],
    'reader.folio' => ['en' => 'Folio', 'ru' => 'Разворот'],
    'reader.line' => ['en' => 'line', 'ru' => 'строка'],
    'reader.lines' => ['en' => 'lines', 'ru' => 'строк'],
    'reader.pages' => ['en' => 'Pages', 'ru' => 'Страницы'],
    'reader.previous_page' => ['en' => 'Previous page', 'ru' => 'Предыдущая страница'],
    'reader.next_page' => ['en' => 'Next page', 'ru' => 'Следующая страница'],
    'reader.page_indicator' => ['en' => 'Page :page of :last', 'ru' => 'Страница :page из :last'],
    'reader.hint' => ['en' => 'Tap a line to reveal its translation · Spacebar toggles audio playback', 'ru' => 'Нажмите на строку, чтобы увидеть перевод · Пробел включает и выключает аудио'],
    'reader.reader_heading' => ['en' => 'Reader', 'ru' => 'Читалка'],
    'reader.library_language' => ['en' => 'Library language', 'ru' => 'Язык библиотеки'],
    'reader.loading' => ['en' => 'Loading', 'ru' => 'Загрузка'],
    'reader.english' => ['en' => 'English', 'ru' => 'Английский'],
    'reader.russian' => ['en' => 'Russian', 'ru' => 'Русский'],
    'reader.no_texts' => ['en' => 'No texts in this language', 'ru' => 'На этом языке текстов нет'],
    'reader.no_texts_hint' => ['en' => 'Switch the language above, or ask an editor to add texts.', 'ru' => 'Переключите язык выше или попросите редактора добавить тексты.'],
    'reader.texts' => ['en' => 'Texts', 'ru' => 'Тексты'],
    'reader.index_hint_open' => ['en' => 'Open a text to read it', 'ru' => 'Откройте текст, чтобы читать'],
    'reader.index_hint_gutter' => ['en' => 'the translation appears across the gutter', 'ru' => 'перевод появится напротив каждой строки'],
    'reader.highlights' => ['en' => 'Highlights', 'ru' => 'Подсветка слов'],
];
